### ISSUE TITLE
missing dependencies during inheritance resolution

### ISSUE THREAD

**Issue by eidng8** [theseer/phpdox#188]
I've got a project using Smarty. I have excluded Smarty from getting into the doc with a `exclude` tag in the collector, because it is out side of my scope, and including it will gets a whole lot of stuffs into my doc. While generating the documentation, I've got the following error:

```
[exec] [04.01.2015 - 15:01:15] The following unit(s) had missing dependencies during inheritance resolution:
[exec] [04.01.2015 - 15:01:15]  - TemplateBase (missing Smarty)
[exec] [04.01.2015 - 15:01:15]  - LandingPage (missing Smarty)
[exec] [04.01.2015 - 15:01:15] Collector process completed
```

So far, the generated document seems OK, except there's a broken link to Smarty. So my question is:
Is there any way to get rid of the Smarty link? Say, by excluding the class, or mark it as external, or something?

**Comment by theseer** [comment]
The message you got is merely a warning and not an exactly error.

Technically speaking, the documentation is incomplete when classes you are relying upon by extending cannot be found/resolved. So even if you exclude smarty - which is of course perfectly valid and legal to do - from the documentation, technically you are using it, thus its API is part of your application and now missing in your docs.

The fact there is a broken link though sounds like a template bug. I'll investigate that since phpDox shouldn't be generating links nor listing classes it has no knowledge of.

Can you provide me with a pointer as to where you found the broken link? Synopsis, class list, extends reference?

**Comment by theseer** [comment]
Nevermind, found it and working on a fix.
