### ISSUE TITLE
clover enricher

### ISSUE THREAD

**Issue by penfold45** [theseer/phpdox#189]
Hi

In src/config/skeleton.xml there is a comment for enrichers that says 

<pre>
&lt;!-- @type - the handler for the enrichment --&gt;
&lt;!-- known types by default are: checkstyle, pmd, clover, phpunit --&gt;
</pre>

However "clover" does not seem to be supported. Am I missing something or is this incorrect.
Do you intend to suppor the clover xml file generated by phpunit or do I have to build the --coverage-xml file to work with phpDox?

**Comment by theseer** [comment]
I originally considered to use clover.xml as source for phpDox but it turned out that it does not contain enough information to be a source for the intended purpose. That's the main reason I created the already mentioned coverage xml code for PHPUnit. So yes, please use said option.

The skeleton config has been corrected with commit d70cae21fa9598ed15e9e620e767812b399aaf3a. Thank you for bringing this to my attention.
