### ISSUE TITLE
nikic/php-parser dependency error

### ISSUE THREAD

**Issue by fahadbillah** [theseer/phpdox#291]
` composer require --dev theseer/phpdox=0.9.0`
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for theseer/phpdox 0.9.0 -> satisfiable by theseer/phpdox[0.9.0].
    - theseer/phpdox 0.9.0 requires nikic/php-parser 3.0.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by theseer** [comment]
As the error message suggests, this is likely a "minimum stability" issue since there is no stable 3.0 release of PHP-Parser yet.

Again, I strongly advise against mixing project and tool dependencies. Simply use the phar distribution of phpDox. If you have phive installed that's as easy as "phive install phpdox".
