### ISSUE TITLE
Multiline annotation for class constants fails to add subsequent lines

### ISSUE THREAD

**Issue by pkollitsch** [theseer/phpdox#320]
I have constants in classes documented as the following sample:

```
/**
 * @constant Invoice is solved - meaning invoice is paid and all related bookings are set to solved
 */
const STATUS_SOLVED = 900;
```
This parses correct. But when I cut the string in two lines (so it's below 80 characters per line) the second and subsequent lines are ignored in the resulting documentation file.

```
/**
 * @constant Invoice is solved - meaning invoice is paid and all related 
 *            bookings are set to solved
 */
const STATUS_SOLVED = 900;
```
Are there any rules that constants have to be documented in one single line?

**Comment by theseer** [comment]
No, that seems to be a bug in the docblock parsing.

**Comment by pkollitsch** [comment]
Just to go sure: with subsequent lines I only mean the multi-line docs for this one constant, not the following constants or parameters documentation.

**Comment by theseer** [comment]
Two side notes regarding the fix for future reference:
- Officially, there is no `@constant` annotation in phpDoc as far as I could find
- The actual parsing implementation wasn't that off - it took the first line as compact summary, the following lines as description body. I changed this to be merged together. All tests are still good but I'm not fully convinced yet that won't break anything...
