### ISSUE TITLE
Git enricher does not work properly with Git 1.7.1

### ISSUE THREAD

**Issue by sebastianbergmann** [theseer/phpdox#325]
When I run
```
$ git clone https://github.com/sebastianbergmann/phpunit.git

$ cd phpunit

$ ant generate-project-documentation
```
on a system that has Git 1.7.1 then the Git enricher leaves the %B placeholder in the generated output.

If I run the same on a system that has Git 2.14.3 then the Git enricher produces useful output.

**Comment by theseer** [comment]
According to this [commit](https://github.com/git/git/commit/1367b12ad623e28546ba40c435015d94e7fbb248) to git, it seems %B is available since 1.7.2-rc0 which would make it a close miss for your version.

As that commit and version is about 7 years old, I'm not sure if I should still add support for it?

**Comment by theseer** [comment]
I guess I'll declare git < 1.7.2 as unsupported. I might add a check for that into the git enricher.

**Comment by sebastianbergmann** [comment]
Makes sense.
