### ISSUE TITLE
[QUESTION] Is there anyway to make a css by ourlself?

### ISSUE THREAD

**Issue by benyaminl** [theseer/phpdox#330]
Hello, I want to ask, is it possible to create css for oursellf and format the output phpdox? Thanks

**Comment by theseer** [comment]
Unfortunately phpDox does not currently allow specifying a custom CSS. Nevertheless, there are various ways to get a custom CSS in place:

- Have your build automation overwrite the default CSS file in the generated html directory

- Extract the template [directory](https://github.com/theseer/phpdox/tree/master/templates/html), modify the static/css files as needed and tell phpDox to use [your template](https://github.com/theseer/phpdox/blob/master/phpdox.xml.dist#L26) rather than the build in one

- Write your own engine, potentially by extending the [HTML Engine](https://github.com/theseer/phpdox/blob/master/src/generator/engine/html/Html.php) and overwriting the `buildFinish` method. You could add or modify static files as needed here.

**Comment by benyaminl** [comment]
Ah thanks for informing me. Thanks



Sent from My Asus Pegasus X005



Pada tanggal Rab, 11 Apr 2018 15.54, Arne Blankerts <
notifications@github.com> menulis:
